### PR TITLE
Switch to kramdown markdown and rouge highlighting

### PR DESCRIPTION
**Pull request by brienna**
Fixes [#38](https://github.com/muan/scribble/issues/38).

These changes are to accommodate [GitHub Pages changes](https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0):
- Starting May 1st, 2016, GitHub Pages will only support kramdown.
- GitHub Pages now only supports Rouge.

### CODE REVIEW

**Comment by JoshCheek** [comment]
The code highlighting stylesheet can be left as it was, the bit that looks different was the spacing around the code. You can fix that by adding `.highlighter-rouge` to the second line, instead of changing every `.highlight` to `.highlighter-roge`.

``` css
.highlight { font-size: 13px; }
.highlighter-rouge, .highlight, .highlight code, .highlight pre  { background: #29281e; }
.highlight code { padding: 0; }
// ...
```

I'd advocate this is better because the output css tags are more general (ie same style sheet can now be used whether highlighting was generated with rouge or pygments) Plus, it makes the PR smaller, which makes it easier for the maintainer to validate and pull.

**Comment by briennakh** [comment]
Thanks, @JoshCheek! 

I reverted my stylesheet edits, then made the edit you suggested, in addition to an edit to `style.css` that was necessary to keep spacing around the code. 

I removed my edits demonstrating correct kramdown markdown (meaning the post will not look the same as before this pull request). If you want to demonstrate correct kramdown markdown, especially with code blocks inside lists, I would suggest to use backticks or tildes instead of liquid tags, due to this [issue](https://github.com/jekyll/jekyll/issues/588).

**Comment by brienna** [comment]
Thanks, @JoshCheek!

I reverted my stylesheet edits, then made the suggested edit, in addition to a couple edits to `style.css` to keep padding around the code. 

I also reverted my markdown edits, then made the minimal necessary edits for the markdown to be correctly converted by kramdown. For the code block inside the list, I changed its markdown from liquid tags to backticks, due to this [issue](https://github.com/jekyll/jekyll/issues/588).

**Comment by muan** [comment]
Hi there! Really sorry about the unresponsiveness. I've merged #46, hopefully that takes care of things. This repository is really out of date by this point. I will probably rewrite it and republish it at some point. Thanks for putting in the work though. Again I'm terribly sorry!

**Pull request closed without merging**
